version: '{build}'
image: Visual Studio 2019

skip_tags: true

branches:
  only:
    - master

cache:
  - Vst3.x

install:
  - ps: |
      if (-Not (Test-Path ".\Vst3.x\public.sdk")) {
        Invoke-WebRequest "https://www.steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip" -OutFile "vstsdk.zip"
        Expand-Archive "vstsdk.zip" "C:\tmp"
        Copy-Item -Path "C:\tmp\VST3 SDK\*" -Destination ".\Vst3.x" -Recurse
      }

build_script:
  - ps: |
      New-Item -ItemType Directory -Path build | Out-Null
      cmake -B build -A Win32 
      msbuild /v:minimal /nologo Tools.sln /property:Configuration=Release
      cd build
      $env:CL="/DRELEASE_VERSION#$env:APPVEYOR_BUILD_NUMBER"
      msbuild /v:minimal /nologo WaveSabre.sln /property:Configuration=Release
      cd ..

after_build:
  - cmd: 7z a -tzip c:\projects\wavesabre\WaveSabre.%APPVEYOR_BUILD_NUMBER%.zip c:\projects\wavesabre\build\vsts\release\*.dll c:\projects\wavesabre\ConvertTheFuck\bin\Release\*.config c:\projects\wavesabre\ConvertTheFuck\bin\Release\*.dll c:\projects\wavesabre\ConvertTheFuck\bin\Release\*.exe c:\projects\wavesabre\ProjectManager\bin\Release\*.config c:\projects\wavesabre\ProjectManager\bin\Release\*.dll c:\projects\wavesabre\ProjectManager\bin\Release\*.exe c:\projects\wavesabre\build\WaveSabreStandAlonePlayer\Release\*.exe

artifacts:
  - path: '*.zip'
    name: wavesabre

deploy:
  provider: GitHub
  auth_token:
    secure: 4PgCYMcujvIT00In2yBlHm9bDx5Sg+XcyNYnaLg+R1qmW2dhtPdlMAr2saR8h8v6
  artifact: wavesabre
  draft: false
  prerelease: true
  description: "WaveSabre - Automated build of Master branch. Includes all compiled binaries in a single zip file."
