version: '{build}'
image: Visual Studio 2019

skip_tags: true

branches:
  only:
    - master

cache:
  - Vst3.x

install:
  - ps: |
      if (-Not (Test-Path ".\Vst3.x\public.sdk")) {
        Invoke-WebRequest "https://web.archive.org/web/20200502121517if_/https://www.steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip" -OutFile "vstsdk.zip"
        Expand-Archive "vstsdk.zip" "C:\tmp"
        Copy-Item -Path "C:\tmp\VST3 SDK\*" -Destination ".\Vst3.x" -Recurse
      }

build_script:
  - ps: |
      New-Item -ItemType Directory -Path build | Out-Null
      cmake -B build -A Win32 
      msbuild /v:minimal /nologo Tools.sln /property:Configuration=Release
      cd build
      $env:CL="/DRELEASE_VERSION#$env:APPVEYOR_BUILD_NUMBER"
      msbuild /v:minimal /nologo WaveSabre.sln /property:Configuration=Release
      cd ..

after_build:
  - mkdir c:\projects\wavesabre\pkg
  - mkdir c:\projects\wavesabre\pkg\VSTs
  - mkdir c:\projects\wavesabre\pkg\Tools
  - copy c:\projects\wavesabre\LICENSE c:\projects\wavesabre\pkg
  - copy c:\projects\wavesabre\README.md c:\projects\wavesabre\pkg
  - copy c:\projects\wavesabre\build\vsts\release\*.dll c:\projects\wavesabre\pkg\VSTs
  - copy c:\projects\wavesabre\ConvertTheFuck\bin\Release\*.config c:\projects\wavesabre\pkg\Tools
  - copy c:\projects\wavesabre\ConvertTheFuck\bin\Release\*.exe c:\projects\wavesabre\pkg\Tools
  - copy c:\projects\wavesabre\ProjectManager\bin\Release\*.config c:\projects\wavesabre\pkg\Tools
  - copy c:\projects\wavesabre\ProjectManager\bin\Release\*.dll c:\projects\wavesabre\pkg\Tools
  - copy c:\projects\wavesabre\ProjectManager\bin\Release\*.exe c:\projects\wavesabre\pkg\Tools
  - copy c:\projects\wavesabre\build\WaveSabreStandAlonePlayer\Release\*.exe c:\projects\wavesabre\pkg\Tools
  - 7z a -tzip c:\projects\wavesabre\WaveSabre.%APPVEYOR_BUILD_NUMBER%.zip c:\projects\wavesabre\pkg\* -r      

artifacts:
  - path: 'WaveSabre*.zip'
    name: wavesabre
    
deploy:
- provider: GitHub
  description: '"WaveSabre - Automated build of Master branch. Includes all compiled binaries in a single zip file'
  auth_token:
    secure: VLHgGqEJuBvYjzV5LPbgMC/D6SpiB8+P3AMN872HSRsW45RLHzoOpv1UhcofKmDQ
  artifact: wavesabre
  prerelease: true
